# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Ryan
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# twitter_username: username
github_username: davidtryan
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Jekyll configuration
# highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# gems:
#   - jekyll-sitemap
# Sass/SCSS


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "David Ryan"
  avatar : "/assets/images/ERI-headshot.jpg"
  bio    : "Biomedical Engineer with a passion for using data to solve complex problems."
  links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/davidtryan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/davidthomasryan"

footer:
  links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/davidtryan"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/davidthomasryan"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/





# # Site wide configuration

# title: David Ryan
# locale: en_US
# description: data science explorations and projects
# # logo: 
# search: true
# #url: http://localhost:4000
# url: https://davidtryan.github.io/


# # Jekyll configuration

# permalink: /:categories/:title/
# markdown: kramdown
# highlighter: rouge
# sass:
#   sass_dir: _sass
#   style: compressed
# gems:
#   - jekyll-sitemap

# kramdown:
#   input: GFM
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..3
#   enable_coderay: false

# include: [".htaccess"]
# exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
# excerpt_separator: ""

# # Site owner
# owner:
#   name: David Ryan
#   avatar: "/assets/images/ERI-headshot.jpg"
#   email: dtr5a@virginia.edu
# #   disqus-shortname: brooksandrewblog
#   twitter: #username
#   facebook: #username
#   github: davidtryan
# #   stackexchange: #http://stackoverflow.com/users/123456/username
#   linkedin: "https://www.linkedin.com/in/davidthomasryan"
#   instagram: #username
#   flickr: #username
#   tumblr: #username
#   google:
#     plus: #username
# #     analytics: "UA-52978786-2"
#     verify:
#     ad-client:
#     ad-slot: 
#   bing-verify:
